### ISSUE TITLE
Add logs

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#104]
Logs are missing for https://ci.centos.org/view/Devtools/job/devtools-che-functional-tests-periodical/218/console.

**Comment by rhopp** [comment]
Just attaching the log from the jenkins job: https://paste.fedoraproject.org/paste/tvAAyX8FxjqkQ7SDGVLSTQ (because we are keeping last x jobs, the link to the jenkins job won't be available in few days)

**Comment by rhopp** [comment]
https://github.com/redhat-developer/che-functional-tests/blob/master/arquillian-extension-che/src/main/java/com/redhat/arquillian/che/service/CheWorkspaceService.java#L150
