### ISSUE TITLE
Create proper performance tests

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#163]
Typical scenario would be create-start-stop-delete workspace.
Tests should be able to run with multiple users from multiple machines and report to zabbix.
We can take inspiration in fabric8-auth perf tests: https://github.com/fabric8-services/fabric8-auth-tests/tree/master/performance/scripts/auth-api-user

Coordination with @pmacik will be probably needed (knowledge share).

**Comment by Katka92** [comment]
Now tests are running, connecting to our account.
To do:
[] run archiving graphs via zabbix
[] clear environment after tests are done
[] measure time taken by starting workspace
