### ISSUE TITLE
Create job running once a day/week against prod-preview (cluster 2a)

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#190]
Run functional tests against prod-preview, (east-2a) twice a day

**Comment by rhopp** [comment]
Please set the timer to twice a day - where one of the daily runs start between midnight and 3 AM UTC. Thanks ;-)

**Comment by rhopp** [comment]
Quick summary for inspiration ;-)
```
PR CHECK (che-functional tests)
    - prod.preview - free-stg (kkanova-osiotest1)           ->          2a
    - prod - 2 (kkanova-osiotest1)
MERGE TO MASTER (rh-che)
    - prod-preview - free-stg (kkanova-osiotest1)           ->          2a
PERIODICAL (che-functional-tests)
    - prod-preview - 2a (preview-testper)
    - prod-preview -                                        ->          free-stg (kkanova-osiotest1)
    - prod                                                  ->          2
PR CHECK (rh-che)
    - prod-preview - 2a (rh-che-automation-preview)
```

**Comment by Katka92** [comment]
Current state:

PR CHECK (che-functional tests)
    - prod.preview - free-stg (kkanova-osiotest1)           ->          2a  
    - prod - 2 (kkanova-osiotest1)                                                                                            DONE
MERGE TO MASTER (rh-che)
    - prod-preview - free-stg (kkanova-osiotest1)           ->          2a
PERIODICAL (che-functional-tests)
    - prod-preview - 2a (preview-testper)                                                                                 DONE
    - prod-preview -                                        ->          free-stg (kkanova-osiotest1)                 DONE
    - prod                                                       ->          2                                                             DONE
PR CHECK (rh-che)
    - prod-preview - 2a (rh-che-automation-preview)

**Comment by rhopp** [comment]
Followup issues: #262 #263
