### ISSUE TITLE
Investigate PT fails

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#261]
https://osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che-start-workspace-2a/54/artifact/che-start-workspace/che-start-workspace-2a-54/che-start-workspace-2a-54-locust-master.log

https://osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che-start-workspace/126/artifact/che-start-workspace/che-start-workspace-126/che-start-workspace-126-locust-master.log

**Comment by rhopp** [comment]
It didn't happen again. Closing this one.
