### ISSUE TITLE
There is something wrong with user account for periodical job on prod-preview

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#262]
This jobs fails probably because something is wrong with user credentials this job is using
https://ci.centos.org/view/Devtools/job/devtools-che-functional-tests-periodical-prod-preview.openshift.io-2a/

**Comment by ScrewTSW** [comment]
status update:
```
jmelis
12:06
Commented on tdancs' message: for the successful decoding the token first needs to be split by the dots and then you can do `base64 -d` on each part

I checked that, the first one has a padding issue, the second one is OK, the third one is broken
```

**Comment by ScrewTSW** [comment]
generating new token, requesting KB to replace `45e975d5-003b-401b-96c3-be9c5117f164`

**Comment by ScrewTSW** [comment]
token updated by @kbsingh , job is finally running as intented.
https://ci.centos.org/view/Devtools/job/devtools-che-functional-tests-periodical-prod-preview.openshift.io-2a/53/console
Failing on `PackageJsonTestCase` 
```
Tests in error: 
  testPackageJsonBayesian(redhat.che.functional.tests.PackageJsonTestCase): Expected condition failed: waiting for wrapped: element ByJQuery("div:contains('Project web-nodejs-sample imported')") to be present (tried for 30 second(s) with 500 MILLISECONDS interval)
```
