### ISSUE TITLE
Investigate periodical tests failures and fix them.

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#263]
Investigate tests failures of periodical test (except for tests against prod-preview 2a - this one has separate issue #262)

This issue may wait until PR #259 is merged.

Related: https://github.com/redhat-developer/che-functional-tests/issues/262

**Comment by Katka92** [comment]
Previous problems with accounts etc were solved. I'll take a look on all periodical jobs.

**Comment by rhopp** [comment]
Closing. We will open new issues for new test failures.
