### ISSUE TITLE
Change host names in zabbix and send PT data to the new hosts

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#271]
Change host names (add prefix `qa-`).
As deleting host deletes all data in there, please consider if that data could be deleted or if it's possible to copy the data to new host

**Comment by Katka92** [comment]
Old hosts should be alive for 1 month after switching PT data to new hosts. Then old hosts can be deleted.
As a part of this PR (because using the same hosts with other QE teams) try to remove metrics that are not needed.
