### ISSUE TITLE
Update READMEs

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#283]
After discussion on Lean coffee 18th June [1] it was decided to maintain Readmes to be up-to-date. This will allow non-team members to get quick main brief what is the repo about. 

Think about what to add to README - link to jenkins job, zabbix? GitHub which stores READMEs is public - is it OK to share these links if they require login? 

- [ ] functional tests
- [x] mount volume tests
- [x] performance tests

[1] https://docs.google.com/document/d/1LM_76Asg_wvfBt7tyg-zlKJzE8fLpz6gxxZAsFlwU4I/edit#heading=h.z6ophrdxlqvw

**Comment by rhopp** [comment]
Readme in che-functionla-tests is present as it is in rh-che/functional-tests. Closing
