### ISSUE TITLE
Discuss docker usage

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#305]
Agree on right approach regarding to Alex advice:
"I think it is better to start che starter as an image then do it programmatically from test code. This approach is easier to maintain."

**Comment by rhopp** [comment]
This consist of few small sub-tasks

- [ ] Decide if tests should expect that che-starter is already running
- [ ] Create scripts for running che-starter in docker image & tests
- [ ] Remove code for starting che-starter from codebase (don't forget dependencies like shrinkwrap)

**Comment by rhopp** [comment]
Closing this one in favor of followup issue #331
