### ISSUE TITLE
Create automated job for testing che master rollout update

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#306]
https://github.com/redhat-developer/rh-che/issues/726

**Comment by rhopp** [comment]
There is already QE issue on this in upstream: https://github.com/eclipse/che/issues/9646
We need to investigate what is being done there and possibly reuse those tests to test rh-che.

**Comment by Katka92** [comment]
There are two upstream test classes which suites perfectly for our needs:
RollingUpdateStrategyWithWorkspacesStartStopTest
RollingUpdateStrategyWithEditorTest

**Comment by rhopp** [comment]
This task may be blocked by https://github.com/redhat-developer/che-functional-tests/issues/323, right @Katka92 ? If so, we would have to prioritize that one and include it in this sprint.

**Comment by Katka92** [comment]
@rhopp you're absolutely right.

**Comment by Katka92** [comment]
To create job for rolling update test it is needed to have rh-che deployed on rdu2c. Scripts need to be adopted to not cause conflict with PR check which runs with same user but creating another project. When test ends, its needed to archive logs and delete rh-che deployment from rdu2c.

**Comment by Katka92** [comment]
Test needs about 6 mins to run.

**Comment by Katka92** [comment]
Don't forget to add description of this test to README.md and add link to the job!

**Comment by Katka92** [comment]
Job is prepared, scripts created. Can not test it because of cluster outage.

**Comment by Katka92** [comment]
Job is running but failing - need to fix.

**Comment by Katka92** [comment]
Changing creds to service account: https://github.com/openshiftio/openshiftio-cico-jobs/pull/886
