### ISSUE TITLE
Pod creation test on OSIO mounting a PV with existing data inside (~500MB)

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/che-functional-tests#307]
That's something similar to https://gist.github.com/rhopp/26b406f6d2e2e889724ff3a11f3fc9a3 but with a PV that has already a lot of files inside (~500MB).

This is related to https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2088

**Comment by ScrewTSW** [comment]
Data with dashed line belongs to the perf job with data in PVC:  
Starting pod: https://zabbix.devshift.net:9443/zabbix/charts.php?fullscreen=0&groupid=36&hostid=11838&graphid=11073  
Stopping pod: https://zabbix.devshift.net:9443/zabbix/charts.php?fullscreen=0&groupid=36&hostid=11838&graphid=11076  
  
Osioperf job: https://osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che-mount-volume-large-2a/
