### ISSUE TITLE
Fix devtools-che-functional-tests-after-rh-che-build-prod-preview.openshift.io job on ci.centos.org

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#309]
https://ci.centos.org/job/devtools-che-functional-tests-after-rh-che-build-prod-preview.openshift.io/

This is the job which should run functional tests (against prod-preview) after successful build of rh-che repo and successful deploy new version of rh-che to prod-preview.

**Comment by rhopp** [comment]
The build was using wrong branch. PR to cico-jobs was created: https://github.com/openshiftio/openshiftio-cico-jobs/pull/731

**Comment by rhopp** [comment]
We are step further, now the failure is as follows:
https://ci.centos.org/job/devtools-che-functional-tests-after-rh-che-build-prod-preview.openshift.io/46/console

**Comment by rhopp** [comment]
Tests are running now, but the credentials are probably bad:
https://ci.centos.org/job/devtools-che-functional-tests-after-rh-che-build-prod-preview.openshift.io/99/console

**Comment by rhopp** [comment]
Change the job configuration to not run, when the master build fails.

**Comment by rhopp** [comment]
Credentials were overriden by new wrapper introduced into our template. 
I've sent a PR which should fix that: https://github.com/openshiftio/openshiftio-cico-jobs/pull/879

**Comment by Katka92** [comment]
This job is deprecated and will be deleted. Closing.
