### ISSUE TITLE
Test stacks added in https://github.com/redhat-developer/rh-che/pull/787

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#329]
We should test all the stacks from https://github.com/redhat-developer/rh-che/pull/787 for basic scenarios (run workspace, build project, code-completion, ...).
Now, when PR check deploys correct version of rh-che, we can use that for (manual) testing.

**Comment by ScrewTSW** [comment]
@rhopp took a look at the stacks while I was on PTO, just did a brief confirmation, PR is good to go.
