### ISSUE TITLE
Not able to change project type via url

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#330]
When running upstream che tests against rdu2c, they successfully import project. But when the PUT request is sent to change project type, it fails (although it changes project type correctly).
Investigate if this behaviour is present while running against actual rh-che/che. 
Logs are here: https://pastebin.com/WZwLq9Ft

**Comment by rhopp** [comment]
This is the endpoint we are calling with PUT request which fails: https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java#L205

**Comment by Katka92** [comment]
The problem was solved by setting correct classpath of project. 

There are two same relative paths with the same file default.json - one in selenium-core and one in selenium-tests. Files are different so the workspace definition used without classpath set correctly didn't match following logic of the test and project import failed.
