### ISSUE TITLE
Screenshots and video from logs

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#341]
Investigate if/how it works in upstream che. Add some screenshots (and videos?) to our tests.
* where
* how
* when
+ possible on-demand?

**Comment by rhopp** [comment]
I would be also interested where the screenshoots are stored in ci.codevnycorp.com jobs.

**Comment by ScrewTSW** [comment]
Changes prepared in upstream: https://github.com/eclipse/che/compare/6.11.x...ScrewTSW:feature-video-recording-ondemand-screenshots?expand=1
