### ISSUE TITLE
It should be easy to execute functional tests using che-functional-tests docker image

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#348]
Something like
`docker run -e KEYCLOAK_TOKEN=kc_token -e OSIO_USERNAME=username ... quay.io/openshiftio/functional-tests`

There could be one caveat - running che-starter. It may be needed to mount /var/run/docker.sock to be able to run docker container with che-starter.

**Comment by ScrewTSW** [comment]
Che functional tests are already running from the dependency image.

**Comment by rhopp** [comment]
We need the tests sources also be included in the dockerfile to be able to run the tests without cloning and mounting the tests source code into the container.

**Comment by rhopp** [comment]
Blocked by: https://github.com/redhat-developer/che-functional-tests/issues/380
