### ISSUE TITLE
Refactor Che-Starter createWorkspace API call to return proper DTO

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/che-functional-tests#350]
`POST <che-starter-url>/workspace/` should return `org.eclipse.che.api.workspace.shared.dto.WorkspaceDto` instead of custom JSON

Influenced project is `fabric8-wit`
https://github.com/fabric8-services/fabric8-wit/blob/master/codebase/che/client.go

**Comment by Katka92** [comment]
Che starter is deprecated and not used anymore. Closing.
