### ISSUE TITLE
Refactor bind logic

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#353]
There is binder in RhCheSeleniumSuiteModule which should be moved to RhCheSeleniumTestHandler:

```
    bindListener(any(), new RhCheWorkspaceTypeListener(binder().getProvider(Injector.class)));
```

**Comment by rhopp** [comment]
@Katka92 Please investigate what this issue is about.

**Comment by Katka92** [comment]
Already solved - new class RhCheSeleniumClassModule was created and is added to modules in test handler class.
