### ISSUE TITLE
Each PR in rh-che should have own deployment on rdu2c

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#357]
Think about way how to preserve deployments from PR check. The deployment should be available for some time to developer to test it. Rewriting it by another PR check is not wanted. 
Ideas: 
- the deployment is created for each PR check and stays there for e.g. 2 days
- each PR should have own deployment, when PR is closed the deployment is deleted (so only PR check of the "A" PR would be able to redeploy the "A" deployment)
Think about the best approach and do it.

**Comment by rhopp** [comment]
Ideally, each PR should have its own namespace/project, in which each subsequent edit of that PR(added commit/push to feature branch) should be redeployed. And this namespace should be deleted, once the PR is closed.
