### ISSUE TITLE
Create periodical job 

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#359]
Create periodical job which should run once a day. It should use same credentials as che-functional periodical test - so be sure that these jobs will not collide. 
The test suite should contain WorksapceTest and some of upstream tests.
As a part of this issue create:
- [ ] jenkins job
- [ ] script to run che-starter and tests

**Comment by rhopp** [comment]
This issue is probably blocked by https://github.com/redhat-developer/rh-che/issues/944.

**Comment by rhopp** [comment]
You don't have to deal with archiving artifacts as part of this issue. I've created new one to tackle that: https://github.com/redhat-developer/che-functional-tests/issues/359
