### ISSUE TITLE
Create mechanism for collecting che-master logs in tests.

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#360]
Create mechanism, which will obtain logs from che-master. This will be helpful mainly for PR check job (as we have access to the openshift cluster, where PR check job is running).
This will probably be implemented in listener and hook to some "after suite" event/method.

**Comment by Katka92** [comment]
Issue created in eclipse/che repo. Closing. https://github.com/eclipse/che/issues/17300
