### ISSUE TITLE
Create periodical tests checking rh-che compatibility with upstream che

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#368]
Such job already exists:
https://ci.codenvycorp.com/view/All/job/rh-che-ci-master 
But this one only checks that rh-che can be compiled with nightly upstream build.
It would be nice to have job, which also tries to deploy rh-che and tries to start workspace.

**Comment by garagatyi** [comment]
Here is a snippet that Roman used on Codenvy CI to grab upstream Che version and change it in RhChe
```shell
CHE_VERSION=$(curl -s https://raw.githubusercontent.com/eclipse/che/master/pom.xml | grep "^    <version>.*</version>$" | awk -F'[><]' '{print $3}')
echo ">>> change upstream version to: $CHE_VERSION"
mvn versions:update-parent  versions:commit -DallowSnapshots=true -DparentVersion=[$CHE_VERSION] -Dmaven.repo.local=${WORKSPACE}/.repository -U
mvn clean install -Dmaven.repo.local=${WORKSPACE}/.repository -U
```

**Comment by rhopp** [comment]
PR to cico-jobs was merged: https://github.com/openshiftio/openshiftio-cico-jobs/pull/864
Job exists: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/

Possible errors/failures will be dealt with in separate issue. Closing.
