### ISSUE TITLE
Include Theia test in our testsuite

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#373]
We were approached by upstream QE to include test for Theia they created in testing scope of Rh-Che.
So far, it's only one [test class](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/TheiaBuildPluginTest.java) and it should be easy to include it in our suite.

**Comment by Katka92** [comment]
There is another issue consuming test from upstream https://github.com/redhat-developer/che-functional-tests/issues/431. Another Che 7 related tests should be part of Cypress test suite. Closing.
