### ISSUE TITLE
Setup notification for failed runs of devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#381]
https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/ should send mail notification of failed tests at least to QE team.

**Comment by Katka92** [comment]
Depends on issue https://github.com/redhat-developer/che-functional-tests/issues/448

**Comment by Katka92** [comment]
Compatibility is now creating PR and sending comments to that. Closing.
