### ISSUE TITLE
Create (possibly) locust tests for stress testing che-server.

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#383]
This tests should run against che-server deployed on dev cluster.

This issue is about creating such suite and running that at least once.

We should think about suitable scenario for this. Preferably without needing to create/having workspaces created.

Periodic job could be (possibly - not necessary) created as part of another issue.

**Comment by rhopp** [comment]
First try should be against rh-che deployed on dev cluster with local keycloak (not connected to OSIO's auth service to not take it down  ;-))

**Comment by ScrewTSW** [comment]
Documentation about communication: https://www.eclipse.org/che/docs/json-rpc.html

**Comment by ScrewTSW** [comment]
Improvement request: https://issues.jboss.org/browse/CRW-161
