### ISSUE TITLE
Remove old jobs for rh-che

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#405]
As far as now we have running periodic tests:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/
we don't need old test (that are continuously failing). 
Update 'almighty yaml' and make housekeeping issue to inform team that resources need to be deleted too. 

Jobs to delete:
devtools-che-functional-tests-periodical-openshift.io-2
devtools-che-functional-tests-periodical-prod-preview.openshift.io-2a
devtools-che-functional-tests-periodical-prod-preview.openshift.io-free-stg

**Comment by ScrewTSW** [comment]
:+1:
