### ISSUE TITLE
Figure out the right ratio of RAM and ServerSideRequestProcessor thread pool size

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#409]
In short:
When the thread pool is too big, memory can be depleted which results in OOM.
When the thread pool is too low, messages are being dropped which can cause intermittent issues.

We should find the right balance for these values using load testing oc che-master, by either using [Locust stress test](https://github.com/ScrewTSW/rh-che/tree/383-create-locust-load-tests-for-OEM-testing/load-tests) or [Sergii's tool ](https://github.com/skabashnyuk/json-rpc-loader). We can probably test directly on prod-preview, as it has almost the same config as prod.

Relevant issues:
https://github.com/eclipse/che/issues/11961
https://github.com/openshiftio/openshift.io/issues/4626
https://github.com/eclipse/che/issues/11459
https://github.com/eclipse/che/issues/12187

**Comment by ScrewTSW** [comment]
Currently there is an issue with rh-che on minishift: https://github.com/redhat-developer/rh-che/issues/1211 which is blocking us from stresstesting rhche on minishift

It is possible to stresstest mini-che but that does not support metrics

Dev cluster is currently limiting amount of active websocket connections to about 150: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2524

**Comment by ScrewTSW** [comment]
Improvement request: https://issues.jboss.org/browse/CRW-161
