### ISSUE TITLE
Fix clean on dev cluster

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#423]
There is clean up job running [1] but started to fail. Add notification on email if the job failes.

[1] https://ci.centos.org/view/Devtools/job/devtools-rh-che-prcheck-cleanup/

**Comment by Katka92** [comment]
Update in almighty: https://github.com/openshiftio/openshiftio-cico-jobs/pull/945
Update in rh-che: https://github.com/redhat-developer/rh-che/pull/1209

**Comment by rhopp** [comment]
Another PR: https://github.com/redhat-developer/rh-che/pull/1243

Left to do: cleanup job is green even though it's failing.

**Comment by Katka92** [comment]
There were PR created to fix that: https://github.com/redhat-developer/rh-che/pull/1218 but now it is out of date. I couldn't merge it because of suggested changes, I'll rebase it and rise discussion again. Thank you

**Comment by Katka92** [comment]
PR merged. Closing.
