### ISSUE TITLE
Create test for Che 7 workspace

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#424]
Create test for checking Che 7 workspace can be created/started. Add it for PR check.
Think about other things that would be good to test and run these tests in appropriate suite.

**Comment by rhopp** [comment]
There are already two test classes about Che7/Theia workspaces. We should review what exactly they are doing and maybe reuse them.
https://github.com/eclipse/che/tree/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia

**Comment by rhopp** [comment]
And also we already have (at least simmilar) issue in here https://github.com/redhat-developer/che-functional-tests/issues/373

**Comment by Katka92** [comment]
@rhopp Thank you very much! That would be nice to be able to reuse this, thanks!
This is similar issue, but I was thinking that we should start with something like reusing WorkspaceTest - just to create and start Che 7 workspace. Testing Theia would be maybe the next step. WDYT?

**Comment by Katka92** [comment]
As a first step we decided to consume upstream test for Theia [1]. There will be some tests in upstream in near future, so we will focus on reusing these ones instead of creating separate ones. 
Closing this issue. You can follow actual progress on consuming first Theia test in issue https://github.com/redhat-developer/che-functional-tests/issues/431.

[1] https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/theia/Che7PreviewStackStartTest.java
