### ISSUE TITLE
`che-start-workspace` job is failing since 16.1.2019

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#425]
https://osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che-start-workspace/ is failing since 16.1.2019

From console:
```
chmod: cannot access ‘users.tokens’: No such file or directory
```
This may be the reason?

**Comment by Katka92** [comment]
These account doesn't accepted new terms and conditions so tokens was not gotten. I've accepted new conditions today. Please check once there is next run of these jobs if problem was solved.

**Comment by Katka92** [comment]
This job is obsolete and should be deleted.

**Comment by ScrewTSW** [comment]
The jobs have been deleted :)
