### ISSUE TITLE
Refactor PR check

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#426]
Clean code in ```rhche/functional-tests/devscripts/run_tests.sh``` to NOT contain any value setting. Set default values of used parameters and enable these defaults values to be overwritten by setting a parameter by flag (e.g. as a USERNAME is set: -u <username>). 
Change all usages of the script to that approach.
As a part of this issue, investigate which dependencies really have to be installed as far as the logic of PR check changed and probably there is no need of some of them.

Hints:
This file ```run_tests.sh``` is used in ```cico_build_deploy_test_rhche.sh``` (which is used by PRcheck and compatibility check). 
The file ```run_tests.sh``` is called from jenkins job for periodic tests directly, so investigate if any changes need to be done there.

**Comment by ScrewTSW** [comment]
done
