### ISSUE TITLE
Archive logs from target

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#443]
Investigate which target parts are valuable and archive them in http://artifacts.ci.centos.org. 

Tip: E.g. messages of exceptions thrown when provision of workspace fails are not in printed into the standard output, no screenshot is captures (using API). This information would me valuable while finding out what happened. You can try it easily from code - try to start two workspaces.

**Comment by rhopp** [comment]
For example right now, even with failed tests, the surefire-reports folder (which is archived) is empty

**Comment by Katka92** [comment]
@rhopp You have done some work here. Could you please describe what is done / need to be done?

**Comment by rhopp** [comment]
I've added failsafe-reports folder.. Now we should take a look if that provides enough value for us :-)

**Comment by Katka92** [comment]
Java tests are gonna be removed soon, we will not invest time here. Closing.
