### ISSUE TITLE
Change logic in compatibility check

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#448]
Move part of code when branch is been rebased. 

Current flow:
 - check if branch exists
 - branch exists - rebase
 - rebase fails - test fails
 - PR is not created

Change that behaviour to:
 - check if branch exists
 - check if PR with that branch exists
 - rebase branch (if fails, test fail)

It would make sense to create PR and send info here that branch can not be rebased.

**Comment by ScrewTSW** [comment]
done
