### ISSUE TITLE
Create dockerfile for performance tests

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#449]
Run performance tests by docker to simplify the way of usage.

**Comment by Katka92** [comment]
What was status of that when you closed? Is dockerfile created?

**Comment by ScrewTSW** [comment]
@Katka92 Yes, https://github.com/redhat-developer/rh-che/pull/1322/files
And there is also a readme section on how to use it.

I've been successful in using the dockerfile to have 8 parallel docker machines run the performance at the same time with much greater connection bandwidth than just running it natively on baremetal. (around 6~7 thousand connections compared to 1000 I was able to do from my laptop natively)
