### ISSUE TITLE
Can not open file while testing Bayesian on pom.xml

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#461]
Can not open file for testing Bayesian in pom.xml file. This issue is intermittent. 
Affected jobs so far: 
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/147/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/146/console

**Comment by ibuziuk** [comment]
@Katka92 any investigation details? why file can not be opened

**Comment by Katka92** [comment]
I don't have details yet from quick look to logs and screenshots. Need to investigate it more deeper. I'll provide more info once I have some.

**Comment by ibuziuk** [comment]
how often the failure happens for this reason and does it correlates with particular clusters ?

**Comment by Katka92** [comment]
It happened two times yesterday, today the job is passing. I've seen that only on 2a cluster yet. I will keep it open for few days and close it if it will not happen again.

**Comment by Katka92** [comment]
Seen again on 1a https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/474/console

**Comment by Katka92** [comment]
Seen again on 1a https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/475/console

**Comment by Katka92** [comment]
Seen on 2
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/702/console

**Comment by Katka92** [comment]
Seen on 2
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/707/console

**Comment by Katka92** [comment]
This issue is same as issue for bayesian package.json test. One issue was created to sum up. https://github.com/redhat-developer/che-functional-tests/issues/509
Closing.
