### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#469]
Flaky suite is failing because of Che 7 test. The UI has changed so the test needs to be fixed.

**Comment by ibuziuk** [comment]
@Katka92 could you please what exactly has been changed in UI?

**Comment by Katka92** [comment]
@ibuziuk There was a check to verify that IDE is opened correctly. It checked project explorer window. Now the project explorer is not opened, so test can not find it and fails. I'm working on a fix right now.

**Comment by Katka92** [comment]
PR for fix: https://github.com/redhat-developer/rh-che/pull/1340

**Comment by Katka92** [comment]
Fix merged. Closing.
