### ISSUE TITLE
Workspace fails to start on prod-preview 2a due to oso-proxy changes required for k8s-image-puller

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#470]
Workspace is created but fails to start immediatelly after creation.
There is an error in a rh-che log
```
{"@timestamp":"2019-04-03T05:52:08.194+00:00","@version":1,"message":"Starting workspace 'osio-ci-preview-rhche-periodical/wksp-3cr5' with id 'workspacewlq2wpdsng0hpo89' by user 'osio-ci-preview-rhche-periodical'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-4","level":"INFO","level_value":20000,"identity_id":"34a25092-f30d-4478-a8f5-771b077e517d"}
{"@timestamp":"2019-04-03T05:52:08.447+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspacewlq2wpdsng0hpo89. Cause: Failure executing: GET at: https://osoproxy.prod-preview.openshift.io/.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-0","level":"WARN","level_value":30000,"identity_id":"34a25092-f30d-4478-a8f5-771b077e517d "}
{"@timestamp":"2019-04-03T05:52:08.590+00:00","@version":1,"message":"Failed to clean up namespace after workspace 'workspacewlq2wpdsng0hpo89' start failing. Cause: Error(s) occurs while cleaning up the namespace. Failure executing: GET at: https://osoproxy.prod-preview.openshift.io/.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-0","level":"WARN","level_value":30000,"identity_id":"34a25092-f30d-4478-a8f5-771b077e517d "}
{"@timestamp":"2019-04-03T05:52:08.605+00:00","@version":1,"message":"Workspace 'osio-ci-preview-rhche-periodical:wksp-3cr5' with id 'workspacewlq2wpdsng0hpo89' start failed","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"WorkspaceSharedPool-0","level":"INFO","level_value":20000,"identity_id":"34a25092-f30d-4478-a8f5-771b077e517d"}
```
It is reproducible with account for periodic tests ```osio-ci-preview-rhche-periodical``` and my personal account ```kkanova-preview```. 
This is not reproducible on production 2a cluster or on dev cluster.

**Comment by ibuziuk** [comment]
@nurali-techie @alexeykazakov guys, could this potentially be related to latest oso-proxy changes?

**Comment by nurali-techie** [comment]
@ibuziuk @Katka92 one point I can observe.

In above log, I can see this ..
`Failure executing: GET at: https://osoproxy.prod-preview.openshift.io`

Does this mean that you trying to make GET call for URL `https://osoproxy.prod-preview.openshift.io`
If yes then this could be side effect of the fact that we have start returning `HTTP 400` from oso_proxy for the **che_call ONLY** which doesn't have namespace_name in URL.

For ex, below call will return HTTP 400 Bad Request:
https://osoproxy.prod-preview.openshift.io/
https://osoproxy.prod-preview.openshift.io/api/
https://osoproxy.prod-preview.openshift.io/api/v1

while valid call could be,
https://osoproxy.prod-preview.openshift.io/api/v1/namespaces/nvirani-preview-che/pods
https://osoproxy.prod-preview.openshift.io/api/v1/namespaces/nvirani-preview-che/services

Do you see that making namespace_name mandatory in oso_proxy causing this issue ??

Note,
namespace_name = value after `/namespaces/` in request url path.

**Comment by Katka92** [comment]
@ibuziuk @nurali-techie I was able to reproduce it manually, creating the worksapce via Dashboard using accounts ```kkanova-preview```, ```osio-ci-preview-rhche-periodical``` both provisioned on 2a and with account ```kkanova-osiotest1``` provisioned on free-stg. 
I can see this:

![Screenshot from 2019-04-03 16-36-26](https://user-images.githubusercontent.com/29278800/55487958-65a0cf00-562f-11e9-9636-e507e9e1f5e8.png)


From my point of view the problem can be the change which made namespace mandatory. If CHE used to call that API without that parameter and it works OK and you say that ```namespace``` becomes mandatory - there can be the problem. Is that change applied only on prod-preview?

**Comment by ibuziuk** [comment]
but we always pass namespce - https://github.com/redhat-developer/rh-che/blob/master/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java#L115

**Comment by nurali-techie** [comment]
@ibuziuk as mentioned in chat, I can see below oso_proxy logs:
```
time="2019-04-03T10:47:42Z" level=info msg="Got header 'Impersonate-User' with value 'e87f54b8-7905-46f9-8055-f987c5b58320'"
time="2019-04-03T10:47:42Z" level=info msg="namespaceName="
time="2019-04-03T10:47:42Z" level=error msg="Invalid path, namespace name is missing in request path"
```
which indicate that che making call to oso_proxy with url something like `https://osoproxy.prod-preview.openshift.io/` which is failing at oso_proxy end with missing namespace name error msg.

**Comment by ibuziuk** [comment]
@Katka92 https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/ seems to be fixed and changes done on oso-proxy side has been reverted. I guess we can close it

**Comment by Katka92** [comment]
@ibuziuk Ok, I'll close that and if it will appear again, we can re-open this issue.

**Comment by nurali-techie** [comment]
@Katka92 @ibuziuk we are still investigating the issue and trying to find root_cause of this issue.  Once we find root_cause, it need to be fixed and re-enable the revert commit at oso_proxy side.

@Katka92 I can't re-open this issue.  I request you to do needful to re-open this issue.

**Comment by ibuziuk** [comment]
@nurali-techie ok, reopening if you think it is needed - this issue was just an indicator that CI on prod-preview is broken (once oso-proxy deployment reverted the issue was fixed)

**Comment by Katka92** [comment]
I'm OK with tracking changes and investigations in this issue if you want. @ibuziuk thank you for reopening the issue.

**Comment by ibuziuk** [comment]
PR with minor refactoring and more logs for namespace usage while che  -> oso-proxy communications - https://github.com/redhat-developer/rh-che/pull/1346

**Comment by ibuziuk** [comment]
Also setting debug level for che on prod-preview - https://gitlab.cee.redhat.com/service/app-interface/merge_requests/327

**Comment by nurali-techie** [comment]
We have done some finding yesterday, here is details of everything.

**First**, we have seen that the call without namespace is coming to oso_proxy with older changes of oso_proxy.  Currently, older version of oso_proxy is running in prod-preview.  Please see the attached logs.
[f8osoproxy-15-h8tnr.log](https://github.com/redhat-developer/che-functional-tests/files/3046367/f8osoproxy-15-h8tnr.log)
To know whether call without namespace_name is happening, please search `"RequestLine":"GET / HTTP/1.1"`  and we can see there are about 10 calls made to oso_proxy without namespace_name.

Second, we have observe all the calls which happened during start_che_workspace.  Here is the log attached.
[che_start_workspace.log](https://github.com/redhat-developer/che-functional-tests/files/3046372/che_start_workspace.log)
We have analyzed all the calls and we found ~50+ calls made to oso_proxy from che during che_start_ws process.  We have checked all calls against oso_proxy (new_changes of `getNamespaceName()` method) are processed fine.  We have find unique calls and added test case in our code, here is link [new_test_case_for_che_calls](https://github.com/fabric8-services/fabric8-oso-proxy/pull/53/files#diff-f0d61f7c912e5503255b37d727b14061R115).

**Third**, from above observation things looks fine at oso_proxy end and from "first" we are sure that oso_proxy getting call without namespace_name.  With above observation, we are making guess that either che or it could be k8s_client which is making call to oso_proxy without namespace_name.  Which is what we bring here https://chat.openshift.io/developers/pl/fb4ketuominb7b78w1zjducnqr

**Next**, we are going to submit this PR https://github.com/fabric8-services/fabric8-oso-proxy/pull/53 with more logs at oso_proxy end.  This should not break che_start_workspace and should capture more logs wrt che_calls to oso_proxy.

**Comment by nurali-techie** [comment]
We have some more finding with outcome of PR https://github.com/fabric8-services/fabric8-oso-proxy/pull/53 which has more logs for che calls.

oso_proxy log is attached for pod for above PR: [f8osoproxy-16-d84cq.log](https://github.com/redhat-developer/che-functional-tests/files/3046774/f8osoproxy-16-d84cq.log)

**event sequence:**
E1: pod started at 2019-04-05T06:37:18Z (line no 25)
E2: che test jenkins job started around Apr 05, 2019 6:48:36 AM
E3: oso_proxy got **first call** from che without namespace_name at 2019-04-05T06:49:28Z (line no 995)
E4: oso_proxy got total 8 calls without namespace and **last call** got at 2019-04-05T06:52:39Z (line no 2137)
E5: che test jenkins job complete at 2019-04-05T06:52:41+00:00

**Note**, che jenkins job is Green.

**che call without namespace_name to oso_proxy analysis:**
Here is relevant logs extracted from oso_proxy logs which contains logs related to call made from che without namespace_name: [che_namespace_name_missing_calls_analysis.log](https://github.com/redhat-developer/che-functional-tests/files/3046793/che_namespace_name_missing_calls_analysis.log)

Here is one of the call with details:
```
* Call-1
LineNo:995
time="2019-04-05T06:49:28Z" level=warning msg="Invalid path, namespace name is missing in request path, host='osoproxy.prod-preview.openshift.io', path='/apis/project.openshift.io/v1/projects/workspacegxkmvndxlph0u1d0', userID='e87f54b8-7905-46f9-8055-f987c5b58320'"

LineNo:1000
{"BackendAddr":"api.starter-us-east-2a.openshift.com","BackendName":"api1","BackendURL":{"Scheme":"https","Opaque":"","User":null,"Host":"api.starter-us-east-2a.openshift.com","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"ClientAddr":"10.130.4.1:45480","ClientHost":"18.212.11.181","ClientPort":"45480","ClientUsername":"-","DownstreamContentSize":461,"DownstreamStatus":403,"DownstreamStatusLine":"403 Forbidden","Duration":25389897,"FrontendName":"api1","OriginContentSize":461,"OriginDuration":24967586,"OriginStatus":403,"OriginStatusLine":"403 Forbidden","Overhead":422311,"RequestAddr":"osoproxy.prod-preview.openshift.io","RequestContentSize":67,"RequestCount":283,"RequestHost":"osoproxy.prod-preview.openshift.io","RequestLine":"DELETE /apis/project.openshift.io/v1/projects/workspacegxkmvndxlph0u1d0 HTTP/1.1","RequestMethod":"DELETE","RequestPath":"/apis/project.openshift.io/v1/projects/workspacegxkmvndxlph0u1d0","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2019-04-05T06:49:28.593689431Z","StartUTC":"2019-04-05T06:49:28.593689431Z","downstream_Cache-Control":"no-store","downstream_Content-Length":"461","downstream_Content-Type":"application/json","downstream_Date":"Fri, 05 Apr 2019 06:49:28 GMT","downstream_X-Content-Type-Options":"nosniff","level":"info","msg":"","origin_Cache-Control":"no-store","origin_Content-Length":"461","origin_Content-Type":"application/json","origin_Date":"Fri, 05 Apr 2019 06:49:28 GMT","origin_X-Content-Type-Options":"nosniff","request_Accept-Encoding":"gzip","request_Authorization":"REDACTED","request_Content-Length":"67","request_Content-Type":"application/json; charset=utf-8","request_Forwarded":"for=18.212.11.181;host=osoproxy.prod-preview.openshift.io;proto=https;proto-version=","request_Target":"https://api.starter-us-east-2a.openshift.com","request_User-Agent":"okhttp/3.9.1","request_X-Forwarded-For":"18.212.11.181","request_X-Forwarded-Host":"osoproxy.prod-preview.openshift.io","request_X-Forwarded-Port":"443","request_X-Forwarded-Proto":"https","time":"2019-04-05T06:49:28Z "}
```
- there are total Eight calls without namespace_name during time of jenkins job run.
- call without namespace_name has request_path=`/apis/project.openshift.io/v1/projects/workspacegxkmvndxlph0u1d0`
- response from openshift for above call is `HTTP 403 forbidden`
- all Eight calls has similar request_path like `/apis/project.openshift.io/v1/projects` and HTTP method is `DELETE`
- all Eight calls get same response from Openshift which is `HTTP 403`

@ibuziuk @Katka92 @amisevsk 
- can you please confirm above calls made from che without namespace_name.
- can you please provide your input on above call, they are all returning `HTTP 403`.

@alexeykazakov @michaelkleinhenz 
we have got new finding where we are getting call without namespace_name other than call for openshift cluster api details (i.e request_path = `/api/v1` ).  So let's wait for che_team response before working to support such calls in oso_proxy.

**Comment by amisevsk** [comment]
@nurali-techie I'm maybe a little confused here, but the API path `/apis/project.openshift.io/v1/projects` is [not namespaced](https://docs.openshift.com/container-platform/3.11/rest_api/apis-project.openshift.io/v1.Project.html#Delete-apis-project.openshift.io-v1-projects-name) (since a project basically *is* a namespace).

OTOH I have no idea where this call is coming from, so we could look into that more.

**Comment by amisevsk** [comment]
Che will use workspace ID as project name when `che.infra.openshift.project` is unset, but this should be overriden by multitenant behaviour.

**Comment by nurali-techie** [comment]
@amisevsk these calls `/apis/project.openshift.io/v1/projects/` returns `HTTP 403` from openshift.  It means even though che calls it there is no effect it making.  In this case, che can stop making these calls (then these call without namespace_name is eliminated) or do something to get away from `HTTP 403`.  But first, your team should find out the originate of the calls.

**Comment by nurali-techie** [comment]
@ibuziuk damenset requirement is blocked due to this issue.  We already know calls from che without namespace_name and analysis of those calls should be known before making any change at oso_proxy.

**Comment by michaelkleinhenz** [comment]
Note: this blocks https://jira.coreos.com/browse/ODC-309.

**Comment by amisevsk** [comment]
I tracked down the `/apis/project.openshift.io/v1/projects/` to [`RemoveProjectOnWorkspaceRemove.java`](https://github.com/eclipse/che/blob/a403dfb06257fa271d90717727459ddc0816e2e0/infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/RemoveProjectOnWorkspaceRemove.java#L74). It takes a `403` to mean the project does not exist (and so does not need successful deletion.

This functionality is not useful to rh-che since our namespaces are predefined. However, this call *also* would not prevent starting workspaces, which is the original issue here. In @Katka92's original description, it is a `GET` call that is failing, and we seemingly have no logs apart from the scant ones given by Che.

**Comment by amisevsk** [comment]
Apart from the above, I've logged every API call made by Che itself during a create/start/stop/delete workspace flow and all of those are namespaced, so I suspect it is something in kubernetes-client that is failing when oso-proxy is patched.

**Comment by amisevsk** [comment]
Diving into the fabric8-kubernetes-client code, there are a number of legitimate automatic calls made to check the API (usually to determine of the cluster its communicating with is, in fact, an OpenShift cluster. I don't think Che (or any service using kubernetes-client) can survive without making *any* namespaced calls.

**Comment by nurali-techie** [comment]
@amisevsk thanks for confirming two things :-)

**First**, for `DELETE /apis/project.openshift.io/v1/projects/`,
> This functionality is not useful to rh-che since our namespaces are predefined. However, this call also would not prevent starting workspaces, which is the original issue here.

I also checked that during che_ws_start, `DELETE /apis/project.openshift.io/v1/projects/` calls are not coming to oso_proxy.  So these calls MAY NOT be root_cause of che_start_ws issue.

**Second**, for k8s_client calls for API,
> Diving into the fabric8-kubernetes-client code, there are a number of legitimate automatic calls made to check the API

Thanks for cross checking this into k8s_client code as this is what we all believe could be root_cause of che_ws_start fails with calls without namespace_name.

Also, in original log, there is a log which indicate that the call to oso_proxy fails with requet_path `/`
```
{"@timestamp":"2019-04-03T05:52:08.590+00:00","@version":1,"message":"Failed to clean up namespace after workspace 'workspacewlq2wpdsng0hpo89' start failing. Cause: Error(s) occurs while cleaning up the namespace. Failure executing: GET at: https://osoproxy.prod-preview.openshift.io/.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-0","level":"WARN","level_value":30000,"identity_id":"34a25092-f30d-4478-a8f5-771b077e517d "}
```

From above, one can MOSTLY conclude that during che_ws_start calls without namespace_name coming from k8s_client which are mainly related to check API and which MOSTLY the root_cause of this issue.

**Comment by nurali-techie** [comment]
We have got some new logs which clearly show there are call come from che for both cases.  Check logs [f8osoproxy-17-pdlzg.log](https://github.com/redhat-developer/che-functional-tests/files/3058663/f8osoproxy-17-pdlzg.log)
Search for `Cache disabled`

Here is for relevant logs for second case, k8s_client calls for API where request_path = `/`
```
time="2019-04-09T10:45:55Z" level=info msg="Cache disabled for this call as 'namespace name' is missing in request path, host='osoproxy.prod-preview.openshift.io', path='/', userID='e87f54b8-7905-46f9-8055-f987c5b58320'"

{"BackendAddr":"api.starter-us-east-2a.openshift.com","BackendName":"api1","BackendURL":{"Scheme":"https","Opaque":"","User":null,"Host":"api.starter-us-east-2a.openshift.com","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"ClientAddr":"10.131.4.1:57178","ClientHost":"174.129.114.152","ClientPort":"57178","ClientUsername":"-","DownstreamContentSize":4265,"DownstreamStatus":200,"DownstreamStatusLine":"200 OK","Duration":61737805,"FrontendName":"api1","OriginContentSize":4265,"OriginDuration":13624771,"OriginStatus":200,"OriginStatusLine":"200 OK","Overhead":48113034,"RequestAddr":"osoproxy.prod-preview.openshift.io","RequestContentSize":0,"RequestCount":68,"RequestHost":"osoproxy.prod-preview.openshift.io","RequestLine":"GET / HTTP/1.1","RequestMethod":"GET","RequestPath":"/","RequestPort":"-","RequestProtocol":"HTTP/1.1","RetryAttempts":0,"StartLocal":"2019-04-09T10:45:55.813604831Z","StartUTC":"2019-04-09T10:45:55.813604831Z","downstream_Cache-Control":"no-store","downstream_Content-Type":"application/json","downstream_Date":"Tue, 09 Apr 2019 10:45:55 GMT","level":"info","msg":"","origin_Cache-Control":"no-store","origin_Content-Type":"application/json","origin_Date":"Tue, 09 Apr 2019 10:45:55 GMT","request_Accept-Encoding":"gzip","request_Authorization":"REDACTED","request_Forwarded":"for=174.129.114.152;host=osoproxy.prod-preview.openshift.io;proto=https;proto-version=","request_Target":"https://api.starter-us-east-2a.openshift.com","request_User-Agent":"okhttp/3.9.1","request_X-Forwarded-For":"174.129.114.152","request_X-Forwarded-Host":"osoproxy.prod-preview.openshift.io","request_X-Forwarded-Port":"443","request_X-Forwarded-Proto":"https","time":"2019-04-09T10:45:55Z"}
```

**Comment by amisevsk** [comment]
Thanks for the additional logs @nurali-techie. I've created issue https://github.com/redhat-developer/rh-che/issues/1349 to address the `DELETE` request coming from rh-che.

**Comment by nurali-techie** [comment]
@amisevsk @ibuziuk we have merge PR https://github.com/fabric8-services/fabric8-oso-proxy/pull/55 (support damenset) and tested successfully.

- che worksapce start from browser works fine
- jenkin job is green https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/
- damenset calls work fine

**Comment by ibuziuk** [comment]
thank you @nurali-techie !
now the ball is on our side - we are going to test both `che` and `k8s-image-puller` flows on prod-preview before promoting oso-proxy changes to prod

**Comment by amisevsk** [comment]
I've checked and everything seems to be working well!

- I manually ran through a create - delete workspace flow for a Che 7 and Che 6 workspace and there were no issues. QA is probably more qualified to test this.
- I scaled up the kubernetes image puller deployment and it was able to create and delete the daemonset in the `k8s-image-puller` namespace, which is great
  - Side note for us: It seems to currently not be working due to some quota weirdness, but that is orthogonal to this issue.

**Comment by nurali-techie** [comment]
@amisevsk @ibuziuk I understand that damenset_requirement related changes from oso_proxy working as expected.  If there are no more things to be done at oso_proxy end then we would like to mark the jira item as done https://jira.coreos.com/browse/ODC-309 .. fine ??

**Comment by nurali-techie** [comment]
@ibuziuk also, after your confirmation, we will promote oso_proxy changes to `prod`.  So waiting for your confirmation ..

**Comment by amisevsk** [comment]
@nurali-techie I don't have access to the coreos jira, but assuming that issue is for oso-proxy-related changes, I'm fine with closing it now, but lets get Ilya's confirmation as well.

Thanks again for your work.

**Comment by nurali-techie** [comment]
@amisevsk yes this jira https://jira.coreos.com/browse/ODC-309 is about changes in oso_proxy to support damenset_requirement.

@ibuziuk waiting for your confirmation to close jira and promote oso_proxy changes to prod.

**Comment by ibuziuk** [comment]
@nurali-techie let's wait an promote oso-proxy changes next week. We need a little bit more testing effort on our end

**Comment by nurali-techie** [comment]
@ibuziuk let me know when you are done with your testing :+1:

**Comment by ibuziuk** [comment]
@nurali-techie we are done with testing. +1 to promote to prod

**Comment by nurali-techie** [comment]
@ibuziuk @amisevsk @alexeykazakov @michaelkleinhenz 
oso_proxy changes promoted to prod with PR https://github.com/openshiftio/saas-openshiftio/pull/1251
I have tested start and stop of che_workspace and it's working fine on prod.

I am closing https://jira.coreos.com/browse/ODC-309 jira.

**Comment by ibuziuk** [comment]
Closing this one also
