### ISSUE TITLE
Rsync fails on periodic jobs

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#472]
There is an intermittent error started happening from today. It fails to do rsync with the message:
```
+ rsync -e 'ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root' -Ha /home/devtools/workspace/devtools-rh-che-periodic-prod-2/ 172.19.3.93:payload
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '172.19.3.93' (ECDSA) to the list of known hosts.
cannot delete non-empty directory: config
could not make way for new regular file: config
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
```
The code is here https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L530

Jobs running on 2 and 1b cluster on production and 2a cluster on prod-preview are affected. 

Some time ago there was a problem that two jobs were executed at a same time and were run on a same node - so they rewrites each others files. Could it be related?

**Comment by ibuziuk** [comment]
@Katka92 @rhopp do you happen to know if this issue has been escalated to the relevant team owning centos ci ?

**Comment by Katka92** [comment]
I haven't reported that to any team yet. I'll create housekeeping issue for that as this is probably something that service delivery could help with.

**Comment by Katka92** [comment]
I've created housekeeping issue so you can follow the conversation here. https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2592

**Comment by riuvshin** [comment]
is that still actual?

**Comment by ibuziuk** [comment]
@riuvshin according to https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2592#note_618891 yes ;-)

**Comment by ppitonak** [comment]
Do you know what this `config` directory contains? After quickly scanning the `devtools-ci-index.yaml` file it seems that only our e2e tests are generating this directory which would mean that we are again mixing files between jobs.

**Comment by ppitonak** [comment]
Somebody reported that the same Duffy nodes are being assigned to two jobs again ... https://bugs.centos.org/view.php?id=14920#c34182

**Comment by Katka92** [comment]
@riuvshin Was any work related to that done? I can not see this error for few weeks. There is no comment on related issues.

**Comment by Katka92** [comment]
Periodic tests were not affected by this issue for few weeks. Closing though there is no information if anything was done to fix that. Will reopen once it appears again.
