### ISSUE TITLE
Che 7 intermittent failure [Java selenium tests]

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#476]
This test started to fail on different issues. Find out the reason and if it is bug in test, stabilise it. 
Issues found:

Can not open IDE
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/c2e1908b-f1f3-40a6-9f57-d04b5faf2455)

Timeout while opening IDE 
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/5348ffa3-f5cd-4102-bd50-203fb5cc4d91)

**Comment by Katka92** [comment]
I've run this test dozens times against production, prod-prevew and developer cluster, but I was not able to reproduce any of these issues.
Today, one job failed on networking issue [1] so it seems networking is not working reliably on Jenkins.
@ibuziuk Do you think this issue can be related to networking? If not, then I don't see why it is failing on jenkins and passes every time when running from my local env. 

[1] 
```
Trying to pull repository quay.io/openshiftio/rhchestage-rh-che-functional-tests-dep ... 
/usr/bin/docker-current: Get https://quay.io/v1/_ping: EOF.
See '/usr/bin/docker-current run --help'.
```

**Comment by ibuziuk** [comment]
/usr/bin/docker-current: Get https://quay.io/v1/_ping: EOF.

this is 100 % quay outage isse

**Comment by Katka92** [comment]
Ok, thank you for your answer.

**Comment by amisevsk** [comment]
The first screenshot here looks like a route flapping issue.

**Comment by Katka92** [comment]
@amisevsk I agree. Our tests for routes on ``` starter-us-east-1b ``` fails from time to time on timeout waiting for a route to be available. The timeout is set to 5 minutes.

**Comment by amisevsk** [comment]
The strange thing is that Che should not mark workspaces as started until the routes return status `200` (once, in our current config), so the first image suggests that the theia route was returning `200` at one point, but returned `503` when the CI tried to load it.

**Comment by Katka92** [comment]
@amisevsk Exactly this is what we can see in some of our route tests. E.g. here https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-route-2a/180/console You can see that one 503 was returned when route should be accessible. 

Che 7 ide fails to load again today 
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/442/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/444/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/444/console

**Comment by Katka92** [comment]
Today I've seen this screen on failed job again [1]. I find out in logs that it tooks ~19 minutes for workspace to start. Seems to be related to slow workspace start https://github.com/redhat-developer/rh-che/issues/1413.

[1] 
![image](https://user-images.githubusercontent.com/29278800/57999905-5a1e4000-7ad7-11e9-923f-14ca4405b002.png)

**Comment by Katka92** [comment]
Failed before creating workspace. 
![image](https://user-images.githubusercontent.com/29278800/58227864-f2613280-7d2c-11e9-93c6-4d85ea3af688.png)

**Comment by Katka92** [comment]
Che 7 failed again, cluster 2 4x, 2a 4x, 1a 4x, 1b 1

**Comment by Katka92** [comment]
Seen again on 2, 2a

**Comment by Katka92** [comment]
Seen again on 2 and 2a.

**Comment by Katka92** [comment]
Seen on 2 and 1b.

**Comment by Katka92** [comment]
Seen on 1a

**Comment by Katka92** [comment]
Test opened wrong tab on prod-previw
![image](https://user-images.githubusercontent.com/29278800/59008935-1d1eb100-882c-11e9-917b-c01bc24b2686.png)

**Comment by Katka92** [comment]
Seen again on 2

**Comment by Katka92** [comment]
We have some new logs in that issue:
![Screenshot from 2019-07-01 10-09-13](https://user-images.githubusercontent.com/29278800/60420726-b00ef900-9be8-11e9-9e80-7419417de37e.png)

Logs from Kibana does say basicaly nothing:
![Screenshot from 2019-07-01 10-12-39](https://user-images.githubusercontent.com/29278800/60420782-d2087b80-9be8-11e9-85ac-d763dba2b394.png)

Seems like the deployment of a workspace pod was not available in 240 seconds.

**Comment by ScrewTSW** [comment]
seen on 1b and 2 again

**Comment by Katka92** [comment]
Failed before creating workspace. https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/794/console

**Comment by ScrewTSW** [comment]
![image](https://user-images.githubusercontent.com/16451875/61361300-8ad4e880-a880-11e9-9293-5447689c1649.png)
The issue surfaced today again on 1b cluster. The project was not being created at all, as if the `Create & Open` button has not received the click even, it was just standing there stuck

**Comment by ScrewTSW** [comment]
Happened today twice, appeared on `1a` and `1b` clusters

**Comment by ScrewTSW** [comment]
happened today twice on `1a` and `1b`

**Comment by Katka92** [comment]
Seen again on 1a, worksapce was not created 8x, workspace start timeout 5x
1b workspace not created 8x, worksapce start timeout 6x

**Comment by ScrewTSW** [comment]
Closing in favor of the rh-che tracking issues.
