### ISSUE TITLE
Increase timeout for periodic job

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#477]
From time to time some job fails on BUILD TIMEOUT. It appeared again [1]. Increase the time out.

[1] https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/279/console

**Comment by Katka92** [comment]
PR for the change: https://github.com/openshiftio/openshiftio-cico-jobs/pull/1005

**Comment by Katka92** [comment]
PR merged. Closing.

**Comment by Katka92** [comment]
Seen again https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/409/console

**Comment by Katka92** [comment]
Seen again https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/425/console

**Comment by Katka92** [comment]
Seen again https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/437/console

**Comment by Katka92** [comment]
Seen again https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/654/console

**Comment by Katka92** [comment]
Seen again
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/657/console (1 wkspc not started, times of other starts are 455, 207, 75 seconds)
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/445/console (1 wksp not started, times of other starts are 290, 203 and 394 seconds)

**Comment by Katka92** [comment]
Seen again due to long workspace startup. We decided to lower waiting time for workspace startup from 10 minutes to 5 minutes.

**Comment by ibuziuk** [comment]
yeah, 5 minutes should be more than enough. If a workspace is not starting in 5 minutes the test should fail

**Comment by Katka92** [comment]
The timeout is set in upstream tests. We have to override the binding to put our custom wait here or have a discussion with upstream team to have it changed e.g. to be set from an environment variable.
I don't think it is worth spending time on that now as it will not have major impact. We can re-open once it would be crucial. Closing.
