### ISSUE TITLE
Remove old logs from artifacts.ci.centos.org

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#480]
The time needed for the page to load of each job increased due to the amount of logs cashed here. Discuss the right amount of logs to keep and remove the old ones in periodic way (at the end of periodic job, as a part of cleanup job that cleans old PR deployments, new cleanup job...).

**Comment by Katka92** [comment]
We decided to leave last 200 runs of each job. It should clean periodic tests + PR check + saas-openshiftio.

**Comment by ScrewTSW** [comment]
deprecated
