### ISSUE TITLE
Fails open Che 6 IDE

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#487]
Periodic tests fails to open IDE. The error message says that project explorer is not present:
```
Caused by: org.openqa.selenium.NoSuchElementException: 
no such element: Unable to locate element: {"method":"id","selector":"gwt-debug-projectTree"}
```
and screenshot shows just black screen [1].

[1] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/397/screenshots/com.redhat.che.functional.tests.BuildAndRunProjectTest.checkWorkspace_time-1557240560799-millis.png

**Comment by Katka92** [comment]
seen again https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/473/console

**Comment by Katka92** [comment]
1b https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/490/console

**Comment by Katka92** [comment]
2 https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/717/console

**Comment by Katka92** [comment]
1a https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/539/console

**Comment by Katka92** [comment]
1a https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/560/console

**Comment by Katka92** [comment]
Seen again on 1a https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/877/console

**Comment by ScrewTSW** [comment]
Related to https://github.com/redhat-developer/rh-che/issues/1511 Closing as duplicate
