### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#488]
When trying to log in, the error is present:
```
Caused by: org.openqa.selenium.NoSuchElementException: 
no such element: Unable to locate element: {"method":"id","selector":"gwt-debug-projectTree"}
  (Session info: chrome=74.0.3729.131)
```
and screenshot:
![image](https://user-images.githubusercontent.com/29278800/57433145-00e12180-7238-11e9-9896-a70f87ea1c4e.png)

Happened only once on 1b [1]. Creating issue to follow next occurence.  

[1] https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/397/console

**Comment by Katka92** [comment]
Not seen again. Closing.

**Comment by Katka92** [comment]
Seen again on 2: https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/937/console

**Comment by ScrewTSW** [comment]
appeared today at `1b`

**Comment by ScrewTSW** [comment]
closing for the sake of rhche issue
