### ISSUE TITLE
Che 7 workspace fails on "unauthorized"

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#489]
Che 7 workspace fails to start on error:
```
Failed create pod sandbox: pc error: code = Unknown desc = Get https://registry.reg-aws.openshift.com:443/v2/openshift3/ose-pod/manifests/v3.11.82: unauthorized: authentication required
```

This error is seen only in UI. You can see it here [1]. In Kibana, this error is not present, the only thing that is shown here is:
```
"message":"Failed to start Kubernetes runtime of workspace workspacertz17qpkyxdtc59t. Cause: Server 'theia' in machine 'ws/theia-ide' not available."
```

[1] 
![image](https://user-images.githubusercontent.com/29278800/57601106-ecfd2e80-755b-11e9-97cb-dc95bc0809ab.png)

**Comment by Katka92** [comment]
Related issue is opened in openshift.io repo https://github.com/openshiftio/openshift.io/issues/2980

**Comment by ibuziuk** [comment]
@Katka92 this looks like infrastructure specific issue. Could you please create a HK with details?

**Comment by Katka92** [comment]
Related HK issue https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2619

**Comment by Katka92** [comment]
Seen again https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/433

**Comment by Katka92** [comment]
Seen again on 1b.

**Comment by Katka92** [comment]
Seen again on 1b https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/617/console

**Comment by Katka92** [comment]
Seen again on 1b https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/626/console

**Comment by Katka92** [comment]
Seen again on 1b 2 times.

**Comment by Katka92** [comment]
Seen again on 1b: workspace ID ` workspacerk34tnzb9v9qidog `.

**Comment by Katka92** [comment]
Seen again, there are two Warning this time:
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container \"b46e730237f9e51f5efdae906575026126ce1b04700f733513b28206535af817\" network for pod \"mkdir-workspaceyku9n9w71r41nw6m\": NetworkPlugin cni failed to set up pod \"mkdir-workspaceyku9n9w71r41nw6m_osio-ci-e2e-004-che\" network: CNI request failed with status 400: 'pods \"mkdir-workspaceyku9n9w71r41nw6m\" not found\n'
Failed create pod sandbox: rpc error: code = Unknown desc = Get https://registry.reg-aws.openshift.com:443/v2/openshift3/ose-pod/manifests/v3.11.82: unauthorized: authentication required
All events from a run: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-1b/742/events_report.txt

**Comment by ScrewTSW** [comment]
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/2f16ff9f-9721-4241-a20e-bdf10f4a5ca5)

I need to extend this issue. There is a permission denied error message during pull of che-java-maven image. Could this be part of the authentication issue?

**Comment by ScrewTSW** [comment]
Closed as fixed
