### ISSUE TITLE
Can not start Che 7 worksapce

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#490]
Che 7 workspace can not be started for user ```osio-ci-preview-testper```. The first error was [1] and from that time it seems to fail on [2]. As Kibana on dsaas-stg is not working, I can not obtain logs from the first fail. I started to run worksapce manually and I can see error in rhche server logs:
```
"message":"Failed to start Kubernetes runtime of workspace workspacegnin4tq8q6virsea. Cause: null","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime"
```
I can reproduce this issue with my personal account.

[1]![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/143814c3-3fe4-42f6-ad79-8319fef52428)

[2] ![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/13e22a99-9bdf-4d5b-89db-b96b2180d400)

**Comment by ibuziuk** [comment]
Any OpenShift events?

**Comment by Katka92** [comment]
From the yesterday afternoon the job is green again. Closing. Will reopen and provide more details once it occurs again.
