### ISSUE TITLE
Fix archiving artefacts on saas PR check

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#492]
Artefacts from the job https://ci.centos.org/job/devtools-saas-openshiftio-pr-check-rh-che/ are not archived to http://artifacts.ci.centos.org/. Fix this.

**Comment by ScrewTSW** [comment]
Fixed docker image build failure: https://github.com/redhat-developer/rh-che/pull/1469

**Comment by ScrewTSW** [comment]
done
