### ISSUE TITLE
Failed to get access token on 1b

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#494]
Tests failed because they can not obtain access token for the user. https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/448/console

**Comment by Katka92** [comment]
Fail to get access token on 2a https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/481/console

**Comment by Katka92** [comment]
Not reproduced for 26 days. Closing.

**Comment by ScrewTSW** [comment]
Failed to get token is back on all clusters.

**Comment by Katka92** [comment]
Seen a gain on 2a (production) https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/877/console

**Comment by ScrewTSW** [comment]
Closing in favour of upstream issue
