### ISSUE TITLE
Remove PR check from che-functional-tests

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#495]
The PR check job should be removed from che-functional-tests repo.

**Comment by Katka92** [comment]
The job is removed from almighty yaml. The tests that are still shown have to me removed manually.

**Comment by ScrewTSW** [comment]
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/50065a4c-f4a1-4070-baa5-5fc57cc62092)

Status checks have been disabled so they should stop preventing us from merging PRs.
Though, as far as I can see, we cannot easily delete the status checks themselves.
I've also disabled the `ghprb` plugin webhooks in our repo.

**Comment by ScrewTSW** [comment]
@Katka92 @rhopp bump.

**Comment by ScrewTSW** [comment]
deprecated
