### ISSUE TITLE
Failed to delete workspace

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#499]
Worksapce was correctly created and started, test passed, workspace was stopped but failed to be deleted.
Kibana logs stops at ``` workspace stopped ``` message, no info about deleting workspace. In tests logs, there is a failure:
```
INFO org.eclipse.che.selenium.core.inject.SeleniumTestHandler - Processing @PreDestroy annotation in com.redhat.che.functional.tests.BuildAndRunProjectTest
ERROR org.eclipse.che.selenium.core.inject.SeleniumTestHandler - Failed to invoke method delete annotated with @PreDestroy in org.eclipse.che.selenium.core.workspace.CheTestWorkspace. Test instance: com.redhat.che.functional.tests.BuildAndRunProjectTest
```
Next workspace failed to start with the message which occure when there is already some running workspace. You can find issue here https://github.com/redhat-developer/che-functional-tests/issues/497.

This happened for workspace ``` workspace1a27cxik15elwny6 ``` in job https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/460/console
``` workspacecywbteo2fu7ebzxt ``` on 1a
``` workspaceuurvchu24ycvj6ko ``` on 1a
``` workspacem9dqnyz9hvmrexbd ``` on 1a

**Comment by Katka92** [comment]
Seen again on 1a ``` workspace40gn7m366lew9c3k ```.

**Comment by Katka92** [comment]
Seen again on 2 ``` workspace3twmocn4qdh472pz ```

**Comment by ScrewTSW** [comment]
This can probably be closed as irrelevant
