### ISSUE TITLE
Test should fail when deleting workspace is not successful

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#500]
Currently the test does not fail when the workspace is not deleted successfully. Change the behaviour. 
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/462/console

**Comment by Katka92** [comment]
Tests are going to be deprecated, we decided not to work on that now.

**Comment by ScrewTSW** [comment]
done
