### ISSUE TITLE
Determine workspace component metric collection strategy

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/che-functional-tests#501]
We need to have a discussion with @l0rd and possibly @amisevsk and @ibuziuk on how we can achieve this goal, what would be the correct approach to gather these metrics.

**Comment by Katka92** [comment]
Related issue https://github.com/eclipse/che/issues/12740

**Comment by Katka92** [comment]
The part of starting a workspace will be handled by upstream Che. To be discussed with @l0rd @sleshchenko

**Comment by Katka92** [comment]
Possibly related issue: https://github.com/eclipse/che/issues/13502

**Comment by ScrewTSW** [comment]
deprecated
