### ISSUE TITLE
Can not open file

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#509]
There are some test failures caused when opening file. Affected tests are Bayesian test (both pom.xml and package.json). 
The cause of the issue is that repository window appears sometimes on a right side [1] and steel focus. 
After discussion with devs we decided not to invest time on fixing that as it fails only in ~10% of runs. 

[1] ![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/8552e18c-f6d5-4eb6-8772-7243348ef160)

**Comment by Katka92** [comment]
2a https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/509/console

**Comment by Katka92** [comment]
Seen again on 1b https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/531/console

**Comment by Katka92** [comment]
Seen on 1b https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/562/console

**Comment by ScrewTSW** [comment]
Closing as irrelevant
