### ISSUE TITLE
Create script for failure statistics

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#516]
If there are some issues with workspace provisioning, it could be useful to run the script that will go through Kibana logs and search for known issues. This script can be run manually in times when there is some serious issue.
The script should use file with messages of know issues as described here: https://github.com/redhat-developer/che-functional-tests/issues/514. The output of that script should be some file with report.

**Comment by ScrewTSW** [comment]
Create a health-check probe for dsaas which would be collecting logs periodically (using oc) and reporting known issues as metrics into a zabbix (Prometheus) graph.

Each known issue would be represented as a separate metric, giving us a periodic look at the health of our production environment

This would mean that we wouldn't be tied to using only our test accounts and would get a much broader sample.

**Comment by ScrewTSW** [comment]
deprecated
