### ISSUE TITLE
[CHE 6] Import project timeout / project not imported

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#519]
It tooks too long for project to be imported. Currently, IDE should be ready in 120 seconds. It timeouts because project has not been imported yet. 
Job: https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/533/console
Screenshot:
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/368ebdcd-8312-48df-b156-983d344996d5)

**Comment by Katka92** [comment]
Project was not imported at all on 1a
![image](https://user-images.githubusercontent.com/29278800/58682482-fdd9dc80-8370-11e9-9565-ddd770b0170a.png)

**Comment by Katka92** [comment]
Project not imported on 2 and 1b. 
Project import timeout on 1b.
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/553/console

**Comment by Katka92** [comment]
Project not imported on 2a preview. https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/805/console

**Comment by Katka92** [comment]
Project import timeouted on 2 https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1024/console
![image](https://user-images.githubusercontent.com/29278800/61270488-1deb2100-a7a2-11e9-9a74-5424c1c09a5c.png)

Project not imported to Theia on prod-preview https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1026/console and https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1027/console
![image](https://user-images.githubusercontent.com/29278800/61270817-0e200c80-a7a3-11e9-8d4a-b5ff9f7087df.png)

**Comment by ScrewTSW** [comment]
This issue appeared twice today during the Redhat E2E test suite against che7 preview 2a cluster

**Comment by ScrewTSW** [comment]
Appeared once today at preview 2a cluster

**Comment by ScrewTSW** [comment]
happened today once at `us-starter-east-2`

**Comment by Katka92** [comment]
Project import timeout seen on 2 https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1091/console

**Comment by ScrewTSW** [comment]
Closing in favor of rhche issue
