### ISSUE TITLE
Build timeout

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#525]
Build timeout started to occur more often now. Investigate why and adjust the timeout if needed. 
It started to happen when there was a problem with workspace startup. Startup takes too much time and it was considered that that's the cause why tests are failing on BUILD TIMEOUT. 
Now, worksapce startup takes only ~35 seconds, so it is obvious that the worksapce startup time is not a cause of this problem. 
Add logs saying how much time each phase consume (e.g. building Rh-Che, deploying Postgre + Rh-Che on dev cluster...) and depending on that optimise the process or increase a timeout.

**Comment by Katka92** [comment]
PR with tracking info created. https://github.com/redhat-developer/rh-che/pull/1459

**Comment by Katka92** [comment]
This job started at 18:56 and was timeouted at 19:06. 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/922/console

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW any investigation details? What are the plans for addressing this issue? Could timeout be related to https://github.com/redhat-developer/che-functional-tests/issues/528

**Comment by Katka92** [comment]
@ibuziuk It can be influenced, but it is not 100% true that once renderer issue is here, the job timeouts. We did some investigations but didn't found anything that should explain the problem. For now, we decided not to invest time there, but get typescript selenium e2e tests in place ASAP. We believe that this issue won't be present with new tests. And if it will occur again when running typescript tests, we will change a priority and try to solve that. Is that OK for you?

**Comment by ibuziuk** [comment]
yes, + 1 for that since e2e happy path is part of our end-game plan - https://gist.github.com/ibuziuk/cd9eac654daac34ac9d139af988bec01#qa-involvement

**Comment by ScrewTSW** [comment]
This issue is very much still present at 2a preview and 2a prod clusters

**Comment by Katka92** [comment]
Seen again on cluster 2, 2a, 1a.

**Comment by ScrewTSW** [comment]
Closing in favor of rhche issue
