### ISSUE TITLE
Timed out receiving message from renderer

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#528]
The tests are failing on renderer timeout. Seems like chrome stopped responding. 
Job with the failure: https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/834/console

Seems like similar problem we had when executing typescript e2e tests from container. Try to add ``` -shm-size=256m ``` to ``` docker run ``` command or check the version of chrome/chromedriver.

**Comment by Katka92** [comment]
Seen on 2, 2a, 1a.
On prod-preview, there was an error  ` chrome not reachable `. We had the problem when running typescript tests and fixed that by adding ` --shm-size=256m `.

**Comment by Katka92** [comment]
Seen again on all prod cluster + ` chrome not reachable ` on 1a.

**Comment by Katka92** [comment]
Seen a gain on ` prod-preview `.

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW any investigation details? What are the plans for addressing this issue?

**Comment by Katka92** [comment]
@ibuziuk We believe that this issue won't be present once we will switch to new typescript tests. So currently we are only monitoring that. If it will occur again when running typescript tests, we will change a priority and try to solve that.

**Comment by ScrewTSW** [comment]
This issue is pretty much always present on our tests, appearing at different clusters some days

**Comment by ScrewTSW** [comment]
Issue appeared today only once on preview 2a cluster.

**Comment by Katka92** [comment]
` Timeout from renderer ` and ` chrome not reachable ` present on cluster 2, 2a, 1a, 1b.

**Comment by ScrewTSW** [comment]
This issue was not seen for a while, closing for now
