### ISSUE TITLE
All workspaces not starting on prod-preview

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#542]
On prod-preview there is ` Failed to start Kubernetes runtime of workspace workspacea66y5ql9liauv91t. Cause: Failure executing: GET at: https://osoproxy.prod-preview.openshift.io/api/v1/namespaces/osio-ci-preview-testper-che/persistentvolumeclaims. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password. ` error. 
All Kibana logs for that workspace:
![Screenshot from 2019-07-10 08-40-25](https://user-images.githubusercontent.com/29278800/60946428-7f1c7b80-a2ee-11e9-8d4a-8cdc573ff7d3.png)

Some of the worskpaces with the same problem (but basically all has this problem): ` workspacehm9fvkob2e88ab3u `, ` workspacet3d2nhi9zxplyhqo `, ` workspaceb6xw161wal6fazav `, ` workspacegh66z5lhojqlw080 `, ` workspacer4lmrtqpp4062bzp `, ` workspaceewg80s2u869mq82n `...

**Comment by ibuziuk** [comment]
@Katka92 could you confirm that test account has edit rights in the namespace?

**Comment by ibuziuk** [comment]
was able to reproduce on prod-preview - 

```
Failure executing: POST at: https://osoproxy.prod-preview.openshift.io/api/v1/namespaces/osio-ci-ee3-preview-che/configmaps. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
```

**Comment by Katka92** [comment]
@ibuziuk I can not verify because I don't have access to toggle. But user id for periodic tests is ` e87f54b8-7905-46f9-8055-f987c5b58320 ` so maybe you can take a look.

**Comment by ibuziuk** [comment]
should be fixed now -  preview token was accidentally updated yesterday, was not needed.
The working token for preview has now been restored.
