### ISSUE TITLE
Use versioning for e2e test images

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#544]
Currently the downstream image is based on latest upstream one. The latest upstream e2e image is build with a new release, but RH-Che is not updated that fast, so it can cause some inconsistencies and failing tests. 
What can be done:
1) Create job for running nightly build, which will test last modifications from upstream. This way we can be prepared when some breaking change appears in upstream which is supposed to be pushed in new released version.

2) Our tests can depend on specific version of upstream tests. E.g. If we have rc-3.0.0 on production, test image should be based not on latest, but on rc-3.0.0 upstream image and tagged by this version too. Therefore our tests will not be broken if there is new release with breaking change. 
So, when building images, we will check versions on prod a prod-preview and build adequate images. When running test, we will check version of RH-Che on that environment and run test image with corresponding version. But this approach will force us to have separate branches in RH-Che and whole process would be more expensive on maintenance. 

The version of running RH-Che can be obtained via curl:
` curl -X OPTIONS --header 'Content-Type: application/json' --header 'Authorization: Bearer <token>' https://che.prod-preview.openshift.io/api/ | jq '.buildInfo' `

**Comment by ScrewTSW** [comment]
done.
