### ISSUE TITLE
[CHE 7] Project on imported prod-preview

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#552]
There is an intermittent issue happening on prod-preview when starting Che 7 worksapce. This issue is seen mainly due to periodic tests. 
The screenshot from tests:
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/a3d6bf34-9e3f-44e0-b7b4-f6f50a89dd95)

I think this is not issue in test, because the same tests runs as a PR check on Che and doesn't have problems with that. I was able to reproduce that once on prod-preview when starting Java Maven with console-java-simple project manually. 
This issue is seen for a week.

**Comment by ibuziuk** [comment]
@Katka92 so, the very same test always passing against upstream and periodically fails with project import against prod-preview ?

**Comment by Katka92** [comment]
Seen again on prod-preview 1x https://github.com/redhat-developer/che-functional-tests/issues/552

@ibuziuk There is a different logic in importing project in upstream tests - upstream is testing rc-4 so they don't have a logic for selecting a project as a project is pre-selected. Lets wait for update to rc-4 and see if the problem remains.

**Comment by ScrewTSW** [comment]
Closed in favor of rhche issue
