### ISSUE TITLE
Collect rh-che logs from periodic tests

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/che-functional-tests#553]
We need to automate collection of logs from che-master the same way as events are taken care of.

 - [ ] Add dsaas SA token to job on ci.centos.org
 - [ ] Modify scripts to collect logs from che-master
 - [ ] Add logs to artifacts

**Comment by Katka92** [comment]
Issue created in eclipse/che repo https://github.com/eclipse/che/issues/17300
