### ISSUE TITLE
Implement test case to test Bayesian LSP with node packaging

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-functional-tests#58]
Test case should add some package to NodeJS application and check whether an error pop up on wrong package. 

Bcs tests now work with Java Vert.x application, this test case should import a node project before test execution and remove it after.

**Comment by Katka92** [comment]
Waiting for fix. Something I have written can be found there https://github.com/Katka92/che-functional-tests/tree/bayesian_test_nodejs in PomTestCase in testPackageJsonBayesian method. Should be splitted into new class.
