### ISSUE TITLE
Fix PomTestCase

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-functional-tests#73]
- sometimes PomTestCase break formatting and type dependency in wrong way. There is a syntax error than. 
- there is only check on occurrence of error marker, but the detailed info of error is not evaluated. Test should work with the detailed info of marker and check whether an error marker is really associated to pom.xml CVE validation

**Comment by rhopp** [comment]
The test is adding dependency with vulnerability into pom.xml, but sometimes on wrong position, thus pom.xml is not valid anymore.
Second issue this test has is that it is looking for _any_ error marker. We have to specify for what error marker it should look (by string comparison for exapmle)

**Comment by Katka92** [comment]
Yes, I found these problems too while trying to add bayesian check for
package.json. I think both test can be in one class, because both are
testing bayesian. Next week I'll have a look. Thank you for your notices.
:)
