### ISSUE TITLE
Implement obtaining of token from credentials

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#78]
Right now, the token is saved in jenkins, but because token is only temporary we have to change that in jenkins every month or so.
We should be able to obtain keycloak token using credentials, which seems to be a better approach, than saving token in jenkins credentials storage.

**Comment by vpavlin** [comment]
@hectorj2f @alexeykazakov Is this possible with our keycloak?

**Comment by alexeykazakov** [comment]
No. I assume the che tests needs a fully functional account that linked to the corresponding OSO account. Which means it has to be a developers.redhat.com account. OSIO doesn't know anything about user's credentials. We are using oath workflow which means user passing credentials via browser to developers.redhat.com directly.
What we could do here is create an offline token (it can be valid for year or so) and issue a refresh token too. The test should refresh the access token using the refresh token before the access (offline) token is expired. No credentials needed.

**Comment by rhopp** [comment]
Solved as part of #81 . Closing.
